### ISSUE TITLE
New Siemens Syngo XA30 does not save to network drive

### ISSUE THREAD

**Issue by bkossows** [gallantlab/realtimefmri#34] opened 2023-11-14 12:14 UTC
Hi, I'm having trouble configuring the DICOM saving using ideacmdtool on Siemens Prisma XA30. I've come across instructions for at least three programs utilizing this option:
https://firmm.readthedocs.io/siemens_ideacmdtool/
https://gallantlab.org/realtimefmri/index.html
https://www.fieldtriptoolbox.org/development/realtime/fmri/

The saving process works correctly for the local directory C:\TEMP, but for a mapped network drive like Y:, no files are being saved. I've tried sharing directories from two different machines, and the mapping generally works fine. Other programs can save to this path, but not ideacmdtool.

Can you offer any advice? Perhaps there's something specific in the new software version causing it not to function as in the VE?

Best regards,
Bartosz Kossowski

**Comment by mvdoc** [comment] 2023-11-14 15:32
Hi, this issue doesn't seem strictly related to our software, as it is probably caused by some differences introduced in the Siemens software, or maybe even the Windows version running on the scanner computer. Unfortunately, there is not a lot of official documentation about ideacmdtool, and you'll have to go by trial and error.

If you are using a docker container with Samba (like the one we have in our repository), I would try playing with the samba configs first. Maybe something has changed in the more "recent" windows version running on the Prisma.

You can also try posting on https://neurostars.org to get more ideas.

I will close this issue as it doesn't relate to our software.

**Closed as completed by mvdoc** 2023-11-14 15:32 UTC
